<%@ Page Title="" Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true" CodeFile="ManageUsers.aspx.cs" Inherits="ManagerPages_ManageUsers" %>

<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="FeaturedContent" Runat="Server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="MainContent" Runat="Server">

    <style type="text/css">
.GridviewDiv {font-size: 50%; font-family: 'Lucida Grande', 'Lucida Sans Unicode', Verdana, Arial, Helevetica, sans-serif; color: #303933;}
.Gridview th{color:#FFFFFF;border-right-color:#abb079;border-bottom-color:#abb079;padding:0.5em 0.5em 0.5em 0.5em;text-align:center}
.Gridview td{border-bottom-color:#f0f2da;border-right-color:#f0f2da;padding:0.5em 0.5em 0.5em 0.5em;}
.Gridview tr{color: Black; background-color: White; text-align:left}
:link,:visited { color: #DF4F13; text-decoration:none }
</style>
    
    
    <asp:SqlDataSource runat="server" ID="SqlDataSource1" ConnectionString="<%$ ConnectionStrings:BazaDeStiriConnectionString %>" 
        SelectCommand="select m.UserId,UserName,Email,IsApproved,RoleName,AddOp as AllowSuggest, CommentOp as AllowComment 
from Memberships m join  Users u on m.userId = u.UserId
join UsersInRoles uir on uir.UserId=u.UserId
join Roles r on r.RoleId = uir.RoleId
join Options o on o.UserId = u.UserId
        where r.RoleName = 'registered_user' " 
        DeleteCommand=" update News set User_Id = null where User_Id = @UserId
                        delete from Comments where User_Id = @UserId
                        delete from Options where UserId = @UserId
                        delete from Profiles where UserId = @UserId
                        delete from UsersInRoles where UserId = @UserId
                        delete from UserProfileData where UserId = @UserId
                        delete  from Users where UserId = @UserId
                        delete  from Memberships where UserId = @UserId
                        
                        
                        "
         >
         <DeleteParameters>
            <asp:ControlParameter ControlID="GridView1" Name="UserId" PropertyName="SelectedValue" />
        </DeleteParameters>
        </asp:SqlDataSource>

    <asp:GridView EnableViewState="true"
          CssClass="Gridview"   CellSpacing="4" AllowPaging ="false" ID="GridView1"  
        AllowSorting="true" CellPadding="2" ForeColor="#333333" 
         runat="server" AutoGenerateColumns="False" 
         AutoGenerateDeleteButton="True"
        GridLines="Both"
         Font-Size="Small"
       DataKeyNames="UserId" OnRowCommand="GridView1_RowCommand" DataSourceID="SqlDataSource1"

        >
         <RowStyle BackColor="#ffffff" ForeColor="#000000"  Font-Size="11px"  />
            <HeaderStyle BackColor="#4a70d0" ForeColor="#ffffff" Font-Size="11px" />
<AlternatingRowStyle BackColor="#c0c0c0" ForeColor="#000000" Font-Size="11px" />
        <Columns>
            <asp:BoundField DataField="UserName" HeaderText="UserName" InsertVisible="False" ReadOnly="True" SortExpression="UserName" HeaderStyle-BorderColor="#CC9966" HeaderStyle-BorderWidth="1px" HeaderStyle-BorderStyle="Solid"/>
            <asp:BoundField DataField="IsApproved" HeaderText="IsApproved" SortExpression="IsApproved"  HeaderStyle-BorderColor="#CC9966" HeaderStyle-BorderWidth="1px" HeaderStyle-BorderStyle="Solid"/>
            <asp:BoundField  DataField="RoleName" HeaderText="Role" SortExpression="RoleName"  HeaderStyle-BorderColor="#CC9966" HeaderStyle-BorderWidth="1px" HeaderStyle-BorderStyle="Solid"/>
            <asp:BoundField  DataField="AllowSuggest" HeaderText="Allow Suggest" SortExpression="AllowSuggest"  HeaderStyle-BorderColor="#CC9966" HeaderStyle-BorderWidth="1px" HeaderStyle-BorderStyle="Solid"/>
            <asp:BoundField  DataField="AllowComment" HeaderText="Allow Comment" SortExpression="AllowComment"  HeaderStyle-BorderColor="#CC9966" HeaderStyle-BorderWidth="1px" HeaderStyle-BorderStyle="Solid"/>


           <asp:TemplateField HeaderText="Block" HeaderStyle-BorderColor="#CC9966" HeaderStyle-BorderWidth="1px" HeaderStyle-BorderStyle="Solid">
               <ItemTemplate>
                   <asp:Button ID="B_Block" CommandName="Block" Text="Block" CommandArgument="<%# ((GridViewRow) Container).RowIndex %>" runat="server" ></asp:Button>
               </ItemTemplate>
           </asp:TemplateField>

            <asp:TemplateField HeaderText="Unblock" HeaderStyle-BorderColor="#CC9966" HeaderStyle-BorderWidth="1px" HeaderStyle-BorderStyle="Solid">
               <ItemTemplate>
                   <asp:Button ID="U_Block" CommandName="Unblock" Text="Unblock" CommandArgument="<%# ((GridViewRow) Container).RowIndex %>" runat="server" ></asp:Button>
               </ItemTemplate>
           </asp:TemplateField>

             <asp:TemplateField HeaderText="Make Editor" HeaderStyle-BorderColor="#CC9966" HeaderStyle-BorderWidth="1px" HeaderStyle-BorderStyle="Solid">
               <ItemTemplate>
                   <asp:Button ID="B_Make" CommandName="Make" Text="Make" CommandArgument="<%# ((GridViewRow) Container).RowIndex %>" runat="server"></asp:Button>
               </ItemTemplate>
           </asp:TemplateField>

            <asp:TemplateField HeaderText="Make Admin" HeaderStyle-BorderColor="#CC9966" HeaderStyle-BorderWidth="1px" HeaderStyle-BorderStyle="Solid">
               <ItemTemplate>
                   <asp:Button ID="B_MakeA" CommandName="MakeA" Text="Make" CommandArgument="<%# ((GridViewRow) Container).RowIndex %>" runat="server"></asp:Button>
               </ItemTemplate>
           </asp:TemplateField>
           
            <asp:TemplateField HeaderText="Allow Suggest" HeaderStyle-BorderColor="#CC9966" HeaderStyle-BorderWidth="1px" HeaderStyle-BorderStyle="Solid">
               <ItemTemplate>
                   <asp:Button ID="B_Suggest" CommandName="AllowSuggest" Text="Allow Suggest" CommandArgument='<%#Eval("UserId") %>' runat="server"></asp:Button>
               </ItemTemplate>
           </asp:TemplateField>

             <asp:TemplateField HeaderText="Block Suggest" HeaderStyle-BorderColor="#CC9966" HeaderStyle-BorderWidth="1px" HeaderStyle-BorderStyle="Solid">
               <ItemTemplate>
                   <asp:Button ID="B_BSuggest" CommandName="BlockSuggest" Text="Block Suggest" CommandArgument='<%#Eval("UserId") %>' runat="server"></asp:Button>
               </ItemTemplate>
           </asp:TemplateField>

            <asp:TemplateField HeaderText="Allow Comments" HeaderStyle-BorderColor="#CC9966" HeaderStyle-BorderWidth="1px" HeaderStyle-BorderStyle="Solid">
               <ItemTemplate>
                   <asp:Button ID="B_Comments" CommandName="AllowComments" Text="Allow Comments" CommandArgument='<%#Eval("UserId") %>' runat="server"></asp:Button>
               </ItemTemplate>
           </asp:TemplateField>

            <asp:TemplateField HeaderText="Block Comments" HeaderStyle-BorderColor="#CC9966" HeaderStyle-BorderWidth="1px" HeaderStyle-BorderStyle="Solid">
               <ItemTemplate>
                   <asp:Button ID="B_BComments" CommandName="BlockComments" Text="Block Comments" CommandArgument='<%#Eval("UserId") %>' runat="server"></asp:Button>
               </ItemTemplate>
           </asp:TemplateField>


        </Columns>
    </asp:GridView>

    <asp:Label ID="lblResult" runat="server" Font-Bold="true"/>
   
</asp:Content>

